/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    LinuxSideBar: [
    {
        type: 'category',
        label: 'Linux',
        // link: {type: 'doc', id: 'introduction'},
        items: [
            {
                type: 'category',
                label: 'Manjaro',
                link : {type:'doc', id: 'Linux/manjaro'},
                items: [
                    {
                        type: 'category',
                        label: 'problems',
                        items: [
                            'Linux/problems/pip_p',
                            'Linux/problems/time'
                        ]
                    }
                    
                ]
            }
        ],},
    ],

    ToolSideBar : [
        {
            type: 'category',
            label : 'Git',
            items : [
                {
                    type: 'autogenerated',
                    dirName: 'tool/git', // '.' means the current docs folder
                },
            ]
        },
        'tool/kitty',
        'tool/tools_list',
        'tool/zsh',
        'tool/wikisystem',
    ],
    envSideBar: [
        {
            type: 'doc',
            id : 'envirments/opengl',
            label : 'OpenGL'
        },
    ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
